config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :routines, only: [:index, :create, :new, :destroy] do
    resources :steps
  end
  resources :users, only: [:show, :edit, :update] 



  get '/oops', to: 'application#oops'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/welcome', to: 'users#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cleansers', to: 'products#cleanser', as: 'cleansers'
  get '/toners', to: 'products#toner'
  get '/masks', to: 'products#mask'
  get '/treatements', to: 'products#treatement'
  get '/essences', to: 'products#essence'
  get '/serums', to: 'products#serum'
  get '/moisturizers', to: 'products#moisturizer'
  get '/oil_cleanses', to: 'products#oil_cleanse'
  get '/lip_treats', to: 'products#lip_treat'
  get '/eye_creams', to: 'products#eye_cream'
  get '/spfs', to: 'products#spf'
  get '/ampules', to: 'products#ampule'

  root to: 'application#home' 
  get '/auth/github/callback'=> 'sessions#create'
  
end

app/models/routine.rb
class Routine < ApplicationRecord
    belongs_to :user
    has_many :steps
    has_many :products, through: :steps
    validates_presence_of :name, :skintype

    def taketime
        self.steps.sum do |step|
            step.duration
        end
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
    before_action :require_login

    def new
        @routine = Routine.new
    end

    def create
        @routine = current_user.routines.build(routine_params)
        if @routine.save
            redirect_to new_routine_step_path(@routine)
        else
            render :new
        end
    end 

    def index
        @routines = current_user.routines
    end

    def destroy
        set_routine
        not_yours(@routine)
        @routine.destroy
        redirect_to routines_path
    end

    private 

    def routine_params
        params.require(:routine).permit(:name, :skintype)
    end 

    def not_yours(routine)
        if session[:user_id] != routine.user.id 
          redirect_to oops_path
        end
    end

    def set_routine
        @routine = Routine.find_by(id: params[:id])
    end

end

app/helpers/routines_helper.rb
module RoutinesHelper
    def format_min(duration)
        "#{duration / 60} hours and #{duration % 60} minutes"
    end 
end

app/views/routines/index.html.erb
<h2>Here Are Your Current Skincare Routines</h2>
<%= link_to "Create New Routine", new_routine_path %>

<h3>You have <%= @routines.count%> routines</h3>
<% @routines.each do |routine| %>
    <h3><%= link_to routine.name, routine_steps_path(routine) %> For <%= routine.skintype %> skin</h3> 
    <%= format_min(routine.taketime) %>
    <p><i><%= routine.steps.count %> steps</i> </p>
<%end%>

app/views/routines/new.html.erb
<h2>Let's Create A New Routine</h2>

<%= render partial: '/errors', locals: { record: @routine} %>

<%= form_for @routine do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :name %><br>

    <%= f.label :SkinType %>
    <div><%= f.select :skintype, options_for_select(["Oily", "Dry", "Normal", "Combo", "Acne Prone", "Mature", "All"])%></div><br>
    <%= f.submit "Create Routine and Add Your Steps" %>
<%end%>