config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :routines, only: [:index, :create, :new, :destroy] do
    resources :steps
  end
  resources :users, only: [:show, :edit, :update] 



  get '/oops', to: 'application#oops'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/welcome', to: 'users#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cleansers', to: 'products#cleanser', as: 'cleansers'
  get '/toners', to: 'products#toner'
  get '/masks', to: 'products#mask'
  get '/treatements', to: 'products#treatement'
  get '/essences', to: 'products#essence'
  get '/serums', to: 'products#serum'
  get '/moisturizers', to: 'products#moisturizer'
  get '/oil_cleanses', to: 'products#oil_cleanse'
  get '/lip_treats', to: 'products#lip_treat'
  get '/eye_creams', to: 'products#eye_cream'
  get '/spfs', to: 'products#spf'
  get '/ampules', to: 'products#ampule'

  root to: 'application#home' 
  get '/auth/github/callback'=> 'sessions#create'
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :routines
    has_many :products
    validates_presence_of :username, :password
    validates_uniqueness_of :username
    has_secure_password
    delegate :name, to: :routine, prefix: true
    delegate :name, to: :product, prefix: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in(@user) 
            redirect_to welcome_path
        else
            render :new
        end
    end

    def show        
        @user =  current_user
        @routines = current_user.routines.count
        @products = current_user.products.count
    end

    def welcome
        @user =  current_user
    end 

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

#beep beep imma sheep please update the git

app/views/users/new.html.erb
<h2> Create An Account</h2>

<%= render partial: '/errors', locals: { record: @user} %>

<%= form_for @user, url: signup_path do |f| %>
    <%= f.label :Username%>
    <div><%= f.text_field :username %></div><br>

    <%= f.label :Password%>
    <div><%= f.password_field :password %></div><br>
    
    <%= f.label :confirm_password%>
    <div><%= f.password_field :password_confirmation %></div><br>
    <%= f.submit %>
<%end%>

app/views/users/show.html.erb
<h2> Welcome Back <%= @user.username%>!</h2>


<p>You have <b><%= @routines%></b> routine(s) and <b><%= @products%></b> product(s)</p>

app/views/users/welcome.html.erb
<h2>Welcome to Routine Maker <%= @user.username%></h2>

Let's get you started! 

<p>First, <%= link_to "Add some of the products you own/use", new_product_path%></p>

<p>Once you've got those logged, <%= link_to "Create your routines", routines_path%></p><br>