config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :routines, only: [:index, :create, :new, :destroy] do
    resources :steps
  end
  resources :users, only: [:show, :edit, :update] 



  get '/oops', to: 'application#oops'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/welcome', to: 'users#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cleansers', to: 'products#cleanser', as: 'cleansers'
  get '/toners', to: 'products#toner'
  get '/masks', to: 'products#mask'
  get '/treatements', to: 'products#treatement'
  get '/essences', to: 'products#essence'
  get '/serums', to: 'products#serum'
  get '/moisturizers', to: 'products#moisturizer'
  get '/oil_cleanses', to: 'products#oil_cleanse'
  get '/lip_treats', to: 'products#lip_treat'
  get '/eye_creams', to: 'products#eye_cream'
  get '/spfs', to: 'products#spf'
  get '/ampules', to: 'products#ampule'

  root to: 'application#home' 
  get '/auth/github/callback'=> 'sessions#create'
  
end

app/models/step.rb
class Step < ApplicationRecord
    belongs_to :routine
    belongs_to :product
    validates_presence_of :name, :duration, :product_id
    delegate :name, to: :product, prefix: true
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
    before_action :require_login

    def new
        grab_routine         
        @step = Step.new
    end

    def create
        @routine = Routine.find_by(id: params[:step][:routine_id])
        @step = Step.new(step_params)
        if @step.save
            redirect_to routine_steps_path(@step.routine)
        else
            render :new
        end
    end 

    def index 
        grab_routine    
        validate_routine  
    end 

    def show
        grab_routine  
        @product = Step.find_by(id: params[:product_id])
        set_step
    end

    def edit
        grab_routine
        set_step
    end

    def update
        grab_routine
        set_step
        if @step.update(step_params)
            redirect_to routine_steps_path(@step.routine)
        else
            render :edit
        end 
    end 

    def destroy
        set_step
        not_yours(@step)
        @step.destroy
        redirect_to routines_path
    end

    private

    def grab_routine
        @routine ||= Routine.find_by(id: params[:routine_id])
    end

    def step_params
        params.require(:step).permit(:name, :product_id, :duration, :routine_id)
    end

    def validate_routine
        redirect_to routines_path unless grab_routine
    end 

    def set_step
        @step = Step.find_by(id: params[:id])
    end

    def set_routine
        @routine = Routine.find_by(id: params[:step][:routine_id])
    end

    def not_yours(step)
        if session[:user_id] != step.routine.user.id
          redirect_to oops_path
        end
    end    
end

app/views/steps/_form.html.erb
<%= form_for step, url: url do |f| %>
    <%= f.label :Step_in_routine%>
    <div><%= f.text_field :name%></div><br>

    <%= f.label :Product_used%>
   <div><%= f.collection_select :product_id, user_product, :id, :name, prompt: true%></div><br>

    <%= f.label :Time_taken_in_minutes%>
    <div><%= f.number_field :duration%></div><br>

    <%= f.hidden_field :routine_id, value: @routine.id %>
    <%= f.submit%>
<%end%>

app/views/steps/edit.html.erb
<h2>Let's Edit  For <i><b><%= @routine.name %></b></i></h2>

<%= render partial: '/errors', locals: { record: @step} %>

<%= render partial: 'form', locals: {step: @step, routine: @routine, url: routine_step_path(@routine, @step)}%>

app/views/steps/index.html.erb
<h2>Routine <%= @routine.name %> </h2>
<%= link_to "Add Another Step", new_routine_step_path(@routine) %>

<% @routine.steps.each.with_index(1) do |step, index|%>
    <h3><%= index %>. <%= step.name%></h3>
    <p><i><%= step.product.brand%>'s</i> <%= step.product.name%> (<%= step.duration %> minutes)</p>
    <%= link_to "More Info", routine_step_path(@routine, step.id)%>
<%end%>

<%= button_to "Destroy Your Routine", routine_path(@routine), method: :delete %>

app/views/steps/new.html.erb
<h2>Let's add a new step to your <i><b><%= @routine.name %></b></i></h2>

<%= render partial: '/errors', locals: { record: @step} %>

<%= render partial: 'form', locals: {step: @step, routine: @routine, url: routine_steps_path(@routine)}%>

app/views/steps/show.html.erb
<h2> <%= @routine.name %></h2>
<h3>Step: <%= @step.name %></h3>


<%= link_to "Edit", edit_routine_step_path(@routine, @step.id)%>

<p><b>Duration:</b> <%= @step.duration%> minutes</p>
<p><b>Product Used:</b><%= @step.product.name%></p>
<%# <p><%= @step.notes%></p>

<%= button_to "Destroy", routine_step_path(@routine, @step), method: :delete %>