config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :routines, only: [:index, :create, :new, :destroy] do
    resources :steps
  end
  resources :users, only: [:show, :edit, :update] 



  get '/oops', to: 'application#oops'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/welcome', to: 'users#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cleansers', to: 'products#cleanser', as: 'cleansers'
  get '/toners', to: 'products#toner'
  get '/masks', to: 'products#mask'
  get '/treatements', to: 'products#treatement'
  get '/essences', to: 'products#essence'
  get '/serums', to: 'products#serum'
  get '/moisturizers', to: 'products#moisturizer'
  get '/oil_cleanses', to: 'products#oil_cleanse'
  get '/lip_treats', to: 'products#lip_treat'
  get '/eye_creams', to: 'products#eye_cream'
  get '/spfs', to: 'products#spf'
  get '/ampules', to: 'products#ampule'

  root to: 'application#home' 
  get '/auth/github/callback'=> 'sessions#create'
  
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :steps
    has_many :routines, through: :steps

    scope :cleanser, -> {where(use_for: 'Cleanser')}
    scope :toner, -> {where(use_for: 'Toner')}
    scope :mask, -> {where(use_for: 'Mask')}
    scope :treatement, -> {where(use_for: 'Treatement')}
    scope :essence, -> {where(use_for: 'Essence')}
    scope :serum, -> {where(use_for: 'Serum')}
    scope :moisturizer, -> {where(use_for: 'Moisturizer')}
    scope :oil_cleanse, -> {where(use_for: 'Oil Cleanser')}
    scope :lip_treat, -> {where(use_for: 'Lip Treatment')}
    scope :eye_cream, -> {where(use_for: 'Eye Cream')}
    scope :spf, -> {where(use_for: 'SPF')}
    scope :ampule, -> {where(use_for: 'Ampule')}
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController  
    before_action :require_login
    
    def new
        @product = Product.new
    end

    def create
        @product = current_user.products.build(product_params)
        if @product.save
            redirect_to products_path(@product)
        else
            render :new
        end
    end 

    def index 
        @products = current_user.products
    end

    def show
        current_user
        set_product
    end 

    def cleanser
        @products = current_user.products.cleanser
        # if @products = Product.cleanser
            render :index
        # else
        #     @error = "There are no products like this"
        #     render :index
        # end

    end

    def toner 
        @products = current_user.products.toner
        render :index
    end

    def mask 
        @products = current_user.products.mask
        render :index
    end

    def treatement 
        @products = current_user.products.treatement
        render :index
    end
    
    def essence 
        @products = current_user.products.essence
        render :index
    end

    def serum 
        @products = current_user.products.serum
        render :index
    end

    def moisturizer 
        @products = current_user.products.moisturizer
        render :index
    end

    def oil_cleanse
        @products = current_user.products.oil_cleanse
        render :index
    end

    def lip_treat 
        @products = current_user.products.lip_treat
        render :index
    end

    def eye_cream 
        @products = current_user.products.eye_cream
        render :index
    end

    def spf 
        @products = current_user.products.spf
        render :index
    end

    def ampule   
        @products = current_user.products.ampule
        render :index
    end

    def edit
      set_product
    end

    def update
       set_product
       @product.update(product_params)
       redirect_to @product
    end

    def destroy
        set_product
        not_yours(@product)
        @product.destroy
        redirect_to products_path
    end

    private 

    def product_params
        params.require(:product).permit(:brand, :name, :use_for, :skintype)
    end 

    def not_yours(product)
        if session[:user_id] != product.user.id 
          redirect_to oops_path
        end
    end

    def set_product
        @product = Product.find_by(id: params[:id])
    end
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <%= f.label :Brand %>
    <div><%= f.text_field :brand %></div><br>

    <%= f.label :Name %>
    <div><%= f.text_field :name %></div><br>
    <%# check box with "New" "Holy Grail" "Like" "Dislike" %>

    <%= f.label :Used_as %>
    <div><%= f.select :use_for, options_for_select(["Cleanser", "Oil Cleanser", "Exfoliator", "Serum", "Essence", "Mask", "Sleeping Mask", "Toner", "Ampule", "Moisturizer", "Lip Treatement", "Treatement", "Eye Cream", "Other"])%></div><br>

    <%= f.label :SkinType %>
   <div><%= f.select :skintype, options_for_select(["Oily", "Dry", "Normal", "Combo", "Acne Prone", "Mature", "All"])%></div><br>
   <%# product notes %>

    <%= f.submit "Add Your Product" %>
<%end%>

app/views/products/edit.html.erb
<h2> Update Your Product</h2>

<%= render partial: '/errors', locals: { record: @product} %>


<%= render 'form' %>

app/views/products/index.html.erb
<h2> Your Products </h2>



<%= link_to "All Products", products_path%> |
<%= link_to "Only Oil Cleansers", oil_cleanses_path%> |
<%= link_to "Only Cleansers", cleansers_path%> |
<%= link_to "Only Toners", toners_path%> |
<%= link_to "Only Treatements", treatements_path%> |
<%= link_to "Only Essences", essences_path%> |
<%= link_to "Only Ampule", ampules_path%> |
<%= link_to "Only Serums", serums_path%> |
<%= link_to "Only Eye Creams", eye_creams_path%> |
<%= link_to "Only Moisturizers", moisturizers_path%> |
<%= link_to "Only Lip Treatements", lip_treats_path%> |
<%= link_to "Only SPF", spfs_path%>|

<p><i><%= @error %></i></p>


<% @products.each.with_index(1) do |product, index| %>
    <h3><%= index %>. <%= product.name%></h3> 
    <p><%= product.use_for%> <%= link_to "More Info", product_path(product.id)%></p>   
<% end %>

|<%= link_to "Add A New Product", new_product_path %>|

app/views/products/new.html.erb
<h2> Add your products </h2>

<%= render partial: '/errors', locals: { record: @product} %>


<%= render 'form' %>

app/views/products/show.html.erb
<h2> <%= @product.name %></h2>
<%# like status  %>

<%= link_to "Edit", edit_product_path(@product.id)%>
<p><b>Made By:</b> <%= @product.brand %></p>
<p><b>Product Type:</b> <%= @product.use_for %></p>
<p><b>For</b> <%= @product.skintype %> Skin</p>
<%# <%= @product.notes%>



<%= button_to "Destroy", @product, method: :delete %>